"""rename hotels to hotel

Revision ID: fc6fd21278f1
Revises: fd256c7c764a
Create Date: 2025-08-29 12:52:40.258914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc6fd21278f1'
down_revision: Union[str, Sequence[str], None] = 'fd256c7c764a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('hotels', 'hotel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('hotels', 'hotel')
    # ### end Alembic commands ###
